[build]
  command = "npm run build"
  publish = "dist"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables are set in Netlify UI
# Required environment variables:
# - VITE_OPENAI_API_KEY
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
